# Generated by Django 5.2.3 on 2025-07-28 17:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcampamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('senior', 'Acampamento Sênior'), ('juvenil', 'Acampamento Juvenil'), ('mirim', 'Acampamento Mirim'), ('servos', 'Acampamento de Servos')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('inicio_inscricoes', models.DateField()),
                ('fim_inscricoes', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('responsavel', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('foi_selecionado', models.BooleanField(default=False)),
                ('pagamento_confirmado', models.BooleanField(default=False)),
                ('inscricao_concluida', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.eventoacampamento')),
                ('paroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='inscricoes.paroquia')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.participante')),
            ],
            options={
                'unique_together': {('participante', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='InscricaoJuvenil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('igreja', models.CharField(max_length=150)),
                ('batizado', models.BooleanField()),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoMirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('igreja', models.CharField(max_length=150)),
                ('batizado', models.BooleanField()),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoSenior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('igreja', models.CharField(max_length=150)),
                ('batizado', models.BooleanField()),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoServos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('igreja', models.CharField(max_length=150)),
                ('batizado', models.BooleanField()),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('transacao_id', models.CharField(blank=True, max_length=100)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao')),
            ],
        ),
        migrations.AddField(
            model_name='eventoacampamento',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='inscricoes.paroquia'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('admin_geral', 'Administrador Geral'), ('admin_paroquia', 'Administrador da Paróquia')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
                ('paroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
