# Generated by Django 4.2.25 on 2025-10-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaogrupo',
            name='funcao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alocacaogrupo',
            name='is_coordenador',
            field=models.BooleanField(default=False),
        ),
    ]
