# Generated by Django 5.2.3 on 2025-08-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='qual_alergia_alimento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual alimento causa alergia?'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='qual_alergia_medicamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento causa alergia?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='qual_alergia_alimento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual alimento causa alergia?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='qual_alergia_medicamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento causa alergia?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='qual_alergia_alimento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual alimento causa alergia?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='qual_alergia_medicamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento causa alergia?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='qual_alergia_alimento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual alimento causa alergia?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='qual_alergia_medicamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento causa alergia?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
    ]
