# Generated by Django 4.2.25 on 2025-10-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_alocacaogrupo_funcao_alocacaogrupo_is_coordenador'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alocacaoministerio',
            index=models.Index(fields=['evento'], name='inscricoes__evento__359e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaoministerio',
            index=models.Index(fields=['ministerio'], name='inscricoes__ministe_e636d5_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaoministerio',
            index=models.Index(fields=['is_coordenador'], name='inscricoes__is_coor_8f299e_idx'),
        ),
    ]
