# Generated by Django 5.2.3 on 2025-07-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_alter_pagamento_metodo_alter_pagamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacampamento',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor da Inscrição'),
        ),
    ]
