# Generated by Django 4.2.25 on 2025-10-06 23:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_alocacaoministerio_inscricoes__evento__359e3a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaprivacidade',
            name='imagem_pagto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem do Pagamento (PIX / instruções)'),
        ),
    ]
