# Generated by Django 5.2.3 on 2025-08-09 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_participante_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token para QR Code'),
        ),
    ]
