# Generated by Django 5.2.3 on 2025-07-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_eventoacampamento_valor_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroquia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_paroquias/'),
        ),
        migrations.AddField(
            model_name='paroquia',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=10),
        ),
    ]
