# Generated by Django 5.2.3 on 2025-08-10 03:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_alter_participante_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaprivacidade',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo'),
        ),
    ]
