# Generated by Django 5.2.3 on 2025-07-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_paroquia_logo_paroquia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacampamento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners_eventos/', verbose_name='Banner do Evento'),
        ),
    ]
