# Generated by Django 5.2.3 on 2025-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_eventoacampamento_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', verbose_name='Comprovante de Pagamento'),
        ),
    ]
