# Generated by Django 5.2.3 on 2025-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_politicaprivacidade_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaprivacidade',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato'),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato'),
        ),
    ]
