# Generated by Django 5.2.3 on 2025-07-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_pagamento_comprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Política de Privacidade')),
                ('imagem_camisa', models.ImageField(upload_to='camisas/', verbose_name='Imagem da Camisa')),
            ],
        ),
    ]
