# Generated by Django 5.2.3 on 2025-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_politicaprivacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaprivacidade',
            name='imagem_1',
            field=models.ImageField(blank=True, null=True, upload_to='politica/', verbose_name='Imagem 1 (opcional)'),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='politica/', verbose_name='Imagem 2 (opcional)'),
        ),
    ]
