# Generated by Django 5.2.3 on 2025-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0008_politicaprivacidade_imagem_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='bairro',
            field=models.CharField(default=1, max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='cidade',
            field=models.CharField(default=1, max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='endereco',
            field=models.CharField(default=1, max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='estado',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default=1, max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='numero',
            field=models.CharField(default=1, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
