# Generated by Django 5.2.3 on 2025-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0009_participante_bairro_participante_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='CEP',
            field=models.CharField(default=1, max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
