# Generated by Django 5.2.3 on 2025-07-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0010_participante_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEventoAcampamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='videos_eventos/')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='inscricoes.eventoacampamento')),
            ],
        ),
    ]
