# Generated by Django 5.2.3 on 2025-07-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0011_videoeventoacampamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_participantes/'),
        ),
    ]
