# Generated by Django 5.2.3 on 2025-07-31 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0012_participante_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricaojuvenil',
            name='igreja',
        ),
        migrations.RemoveField(
            model_name='inscricaomirim',
            name='igreja',
        ),
        migrations.RemoveField(
            model_name='inscricaosenior',
            name='igreja',
        ),
        migrations.RemoveField(
            model_name='inscricaoservos',
            name='igreja',
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='casado_na_igreja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='crismado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='dizimista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='medicamento_controlado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='problema_saude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='tamanho_camisa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='casado_na_igreja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='crismado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='dizimista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='medicamento_controlado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='problema_saude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='tamanho_camisa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='casado_na_igreja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='crismado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='dizimista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='medicamento_controlado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='problema_saude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='tamanho_camisa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='casado_na_igreja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='crismado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='dizimista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='medicamento_controlado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='problema_saude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='tamanho_camisa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='batizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='batizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='batizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='batizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('grau_parentesco', models.CharField(max_length=50)),
                ('ja_e_campista', models.BooleanField(default=False)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='inscricoes.inscricao')),
            ],
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento'),
        ),
    ]
