# Generated by Django 5.2.3 on 2025-07-31 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0013_pastoralmovimento_remove_inscricaojuvenil_igreja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='qual_medicamento_controlado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento controlado?'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saúde?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='qual_medicamento_controlado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento controlado?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saúde?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='qual_medicamento_controlado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento controlado?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saúde?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='qual_medicamento_controlado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual medicamento controlado?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='batizado',
            field=models.BooleanField(default=False, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='casado_na_igreja',
            field=models.BooleanField(default=False, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='crismado',
            field=models.BooleanField(default=False, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='dizimista',
            field=models.BooleanField(default=False, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicado Por'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Outra Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='Paróquia'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento', verbose_name='Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui algum problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XGG', 'XGG')], max_length=5, null=True, verbose_name='Tamanho da Camisa'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='batizado',
            field=models.BooleanField(default=False, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='casado_na_igreja',
            field=models.BooleanField(default=False, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='crismado',
            field=models.BooleanField(default=False, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='dizimista',
            field=models.BooleanField(default=False, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicado Por'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Outra Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='Paróquia'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento', verbose_name='Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui algum problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XGG', 'XGG')], max_length=5, null=True, verbose_name='Tamanho da Camisa'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='batizado',
            field=models.BooleanField(default=False, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='casado_na_igreja',
            field=models.BooleanField(default=False, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='crismado',
            field=models.BooleanField(default=False, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='dizimista',
            field=models.BooleanField(default=False, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicado Por'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Outra Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='Paróquia'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento', verbose_name='Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui algum problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XGG', 'XGG')], max_length=5, null=True, verbose_name='Tamanho da Camisa'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='batizado',
            field=models.BooleanField(default=False, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='casado_na_igreja',
            field=models.BooleanField(default=False, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='conjuge_inscrito',
            field=models.BooleanField(default=False, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='crismado',
            field=models.BooleanField(default=False, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='dizimista',
            field=models.BooleanField(default=False, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='indicado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicado Por'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='outra_pastoral_movimento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Outra Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='Paróquia'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='pastoral_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.pastoralmovimento', verbose_name='Pastoral/Movimento'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui algum problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XGG', 'XGG')], max_length=5, null=True, verbose_name='Tamanho da Camisa'),
        ),
    ]
