# Generated by Django 5.2.3 on 2025-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0014_inscricaojuvenil_qual_medicamento_controlado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='É batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
    ]
