# Generated by Django 5.2.3 on 2025-08-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0015_alter_inscricaojuvenil_batizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='grau_parentesco',
            field=models.CharField(choices=[('mae', 'Mãe'), ('pai', 'Pai'), ('irmao', 'Irmão'), ('tio', 'Tio'), ('tia', 'Tia'), ('outro', 'Outro')], max_length=20),
        ),
    ]
