# Generated by Django 5.2.3 on 2025-08-02 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0016_alter_contato_grau_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ja_e_campista', models.BooleanField(default=False)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conjuge', to='inscricoes.inscricao')),
            ],
        ),
    ]
