# Generated by Django 5.2.3 on 2025-08-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0017_conjuge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuge',
            name='conjuge_inscrito',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Cônjuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='conjuge',
            name='ja_e_campista',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Já é Campista?'),
        ),
    ]
