# Generated by Django 5.2.3 on 2025-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0018_conjuge_conjuge_inscrito_alter_conjuge_ja_e_campista'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='contato_emergencia_grau_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='contato_emergencia_ja_e_campista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='contato_emergencia_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='contato_emergencia_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_1_grau_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_1_ja_e_campista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_1_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_1_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_2_grau_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_2_ja_e_campista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_2_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_2_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
