# Generated by Django 5.2.3 on 2025-08-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0019_inscricao_contato_emergencia_grau_parentesco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem diabetes?'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem pressão alta?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem diabetes?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem pressão alta?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem diabetes?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem pressão alta?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem diabetes?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem pressão alta?'),
        ),
    ]
