# Generated by Django 5.2.3 on 2025-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0020_inscricaojuvenil_diabetes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrachaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('imagem_fundo', models.ImageField(upload_to='crachas_templates/', verbose_name='Imagem de Fundo')),
            ],
        ),
    ]
