# Generated by Django 5.1.6 on 2025-08-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0021_crachatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='inscricao_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
