# Generated by Django 5.1.6 on 2025-08-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0022_inscricao_inscricao_enviada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuge',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge'),
        ),
    ]
