# Generated by Django 5.2.3 on 2025-08-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0023_alter_conjuge_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Token de acesso gerado no painel do Mercado Pago', max_length=255, verbose_name='Access Token')),
                ('public_key', models.CharField(help_text='Public Key do Mercado Pago', max_length=255, verbose_name='Public Key')),
                ('sandbox_mode', models.BooleanField(default=True, help_text='Use modo sandbox para testes', verbose_name='Sandbox')),
                ('paroquia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_config', to='inscricoes.paroquia')),
            ],
        ),
    ]
