# Generated by Django 5.2.3 on 2025-08-06 17:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0024_mercadopagoconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crachatemplate',
            name='imagem_fundo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem de Fundo'),
        ),
        migrations.AlterField(
            model_name='eventoacampamento',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Banner do Evento'),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo da Paróquia'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto do Participante'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='imagem_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem 1 (opcional)'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='imagem_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem 2 (opcional)'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='imagem_camisa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem da Camisa'),
        ),
        migrations.AlterField(
            model_name='videoeventoacampamento',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Vídeo do Evento'),
        ),
    ]
