# Generated by Django 5.2.3 on 2025-08-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0025_alter_crachatemplate_imagem_fundo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricaojuvenil',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='inscricaojuvenil',
            name='pressao_alta',
        ),
        migrations.RemoveField(
            model_name='inscricaomirim',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='inscricaomirim',
            name='pressao_alta',
        ),
        migrations.RemoveField(
            model_name='inscricaosenior',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='inscricaosenior',
            name='pressao_alta',
        ),
        migrations.RemoveField(
            model_name='inscricaoservos',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='inscricaoservos',
            name='pressao_alta',
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras (qualquer detalhe relevante não coberto acima)'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui limitações físicas ou mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administração'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitação/mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'Não sei')], max_length=3, null=True, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras (qualquer detalhe relevante não coberto acima)'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui limitações físicas ou mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administração'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitação/mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'Não sei')], max_length=3, null=True, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras (qualquer detalhe relevante não coberto acima)'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui limitações físicas ou mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administração'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitação/mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'Não sei')], max_length=3, null=True, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='Informações extras (qualquer detalhe relevante não coberto acima)'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Possui limitações físicas ou mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administração'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitação/mobilidade reduzida?'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'Não sei')], max_length=3, null=True, verbose_name='Tipo Sanguíneo'),
        ),
    ]
